################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Each subdirectory must supply rules for building sources it contributes
ku/logic/Eggtimer.obj: ../ku/logic/Eggtimer.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"C:/ti/ccsv5/tools/compiler/msp430_4.2.1/bin/cl430" --cmd_file="C:\Users\Ilya\Dropbox\Sports Watch\simpliciti\Applications\configuration\smpl_nwk_config.dat" --cmd_file="C:\Users\Ilya\Dropbox\Sports Watch\simpliciti\Applications\configuration\End Device\smpl_config.dat"  -vmspx --abi=coffabi -O4 --opt_for_speed=0 --include_path="C:/ti/ccsv5/ccs_base/msp430/include" --include_path="C:/ti/ccsv5/tools/compiler/msp430_4.2.1/include" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/include" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/logic" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/driver" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/bluerobin" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Applications/application/End Device" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Components/bsp" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Components/bsp/boards" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Components/bsp/boards/CC430EM" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Components/bsp/boards/CC430EM/bsp_external" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Components/bsp/drivers" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Components/bsp/drivers/code" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Components/bsp/mcus" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Components/mrfi" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Components/mrfi/radios" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Components/mrfi/radios/family5" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Components/mrfi/smartrf" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Components/nwk" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Components/nwk_applications" -g --define=__CC430F6137__ --define=__CCE__ --define=ISM_EU --define=MRFI_CC430 --diag_warning=225 --display_error_number --diag_wrap=off --silicon_errata=CPU18 --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU23 --silicon_errata=CPU40 --call_assumptions=0 --gen_opt_info=2 --printf_support=minimal --preproc_with_compile --preproc_dependency="ku/logic/Eggtimer.pp" --obj_directory="ku/logic" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

ku/logic/_stopwatch.obj: ../ku/logic/_stopwatch.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"C:/ti/ccsv5/tools/compiler/msp430_4.2.1/bin/cl430" --cmd_file="C:\Users\Ilya\Dropbox\Sports Watch\simpliciti\Applications\configuration\smpl_nwk_config.dat" --cmd_file="C:\Users\Ilya\Dropbox\Sports Watch\simpliciti\Applications\configuration\End Device\smpl_config.dat"  -vmspx --abi=coffabi -O4 --opt_for_speed=0 --include_path="C:/ti/ccsv5/ccs_base/msp430/include" --include_path="C:/ti/ccsv5/tools/compiler/msp430_4.2.1/include" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/include" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/logic" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/driver" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/bluerobin" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Applications/application/End Device" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Components/bsp" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Components/bsp/boards" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Components/bsp/boards/CC430EM" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Components/bsp/boards/CC430EM/bsp_external" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Components/bsp/drivers" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Components/bsp/drivers/code" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Components/bsp/mcus" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Components/mrfi" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Components/mrfi/radios" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Components/mrfi/radios/family5" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Components/mrfi/smartrf" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Components/nwk" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Components/nwk_applications" -g --define=__CC430F6137__ --define=__CCE__ --define=ISM_EU --define=MRFI_CC430 --diag_warning=225 --display_error_number --diag_wrap=off --silicon_errata=CPU18 --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU23 --silicon_errata=CPU40 --call_assumptions=0 --gen_opt_info=2 --printf_support=minimal --preproc_with_compile --preproc_dependency="ku/logic/_stopwatch.pp" --obj_directory="ku/logic" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

ku/logic/acceleration.obj: ../ku/logic/acceleration.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"C:/ti/ccsv5/tools/compiler/msp430_4.2.1/bin/cl430" --cmd_file="C:\Users\Ilya\Dropbox\Sports Watch\simpliciti\Applications\configuration\smpl_nwk_config.dat" --cmd_file="C:\Users\Ilya\Dropbox\Sports Watch\simpliciti\Applications\configuration\End Device\smpl_config.dat"  -vmspx --abi=coffabi -O4 --opt_for_speed=0 --include_path="C:/ti/ccsv5/ccs_base/msp430/include" --include_path="C:/ti/ccsv5/tools/compiler/msp430_4.2.1/include" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/include" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/logic" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/driver" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/bluerobin" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Applications/application/End Device" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Components/bsp" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Components/bsp/boards" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Components/bsp/boards/CC430EM" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Components/bsp/boards/CC430EM/bsp_external" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Components/bsp/drivers" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Components/bsp/drivers/code" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Components/bsp/mcus" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Components/mrfi" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Components/mrfi/radios" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Components/mrfi/radios/family5" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Components/mrfi/smartrf" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Components/nwk" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Components/nwk_applications" -g --define=__CC430F6137__ --define=__CCE__ --define=ISM_EU --define=MRFI_CC430 --diag_warning=225 --display_error_number --diag_wrap=off --silicon_errata=CPU18 --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU23 --silicon_errata=CPU40 --call_assumptions=0 --gen_opt_info=2 --printf_support=minimal --preproc_with_compile --preproc_dependency="ku/logic/acceleration.pp" --obj_directory="ku/logic" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

ku/logic/alarm.obj: ../ku/logic/alarm.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"C:/ti/ccsv5/tools/compiler/msp430_4.2.1/bin/cl430" --cmd_file="C:\Users\Ilya\Dropbox\Sports Watch\simpliciti\Applications\configuration\smpl_nwk_config.dat" --cmd_file="C:\Users\Ilya\Dropbox\Sports Watch\simpliciti\Applications\configuration\End Device\smpl_config.dat"  -vmspx --abi=coffabi -O4 --opt_for_speed=0 --include_path="C:/ti/ccsv5/ccs_base/msp430/include" --include_path="C:/ti/ccsv5/tools/compiler/msp430_4.2.1/include" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/include" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/logic" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/driver" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/bluerobin" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Applications/application/End Device" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Components/bsp" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Components/bsp/boards" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Components/bsp/boards/CC430EM" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Components/bsp/boards/CC430EM/bsp_external" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Components/bsp/drivers" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Components/bsp/drivers/code" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Components/bsp/mcus" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Components/mrfi" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Components/mrfi/radios" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Components/mrfi/radios/family5" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Components/mrfi/smartrf" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Components/nwk" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Components/nwk_applications" -g --define=__CC430F6137__ --define=__CCE__ --define=ISM_EU --define=MRFI_CC430 --diag_warning=225 --display_error_number --diag_wrap=off --silicon_errata=CPU18 --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU23 --silicon_errata=CPU40 --call_assumptions=0 --gen_opt_info=2 --printf_support=minimal --preproc_with_compile --preproc_dependency="ku/logic/alarm.pp" --obj_directory="ku/logic" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

ku/logic/altitude.obj: ../ku/logic/altitude.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"C:/ti/ccsv5/tools/compiler/msp430_4.2.1/bin/cl430" --cmd_file="C:\Users\Ilya\Dropbox\Sports Watch\simpliciti\Applications\configuration\smpl_nwk_config.dat" --cmd_file="C:\Users\Ilya\Dropbox\Sports Watch\simpliciti\Applications\configuration\End Device\smpl_config.dat"  -vmspx --abi=coffabi -O4 --opt_for_speed=0 --include_path="C:/ti/ccsv5/ccs_base/msp430/include" --include_path="C:/ti/ccsv5/tools/compiler/msp430_4.2.1/include" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/include" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/logic" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/driver" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/bluerobin" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Applications/application/End Device" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Components/bsp" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Components/bsp/boards" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Components/bsp/boards/CC430EM" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Components/bsp/boards/CC430EM/bsp_external" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Components/bsp/drivers" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Components/bsp/drivers/code" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Components/bsp/mcus" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Components/mrfi" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Components/mrfi/radios" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Components/mrfi/radios/family5" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Components/mrfi/smartrf" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Components/nwk" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Components/nwk_applications" -g --define=__CC430F6137__ --define=__CCE__ --define=ISM_EU --define=MRFI_CC430 --diag_warning=225 --display_error_number --diag_wrap=off --silicon_errata=CPU18 --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU23 --silicon_errata=CPU40 --call_assumptions=0 --gen_opt_info=2 --printf_support=minimal --preproc_with_compile --preproc_dependency="ku/logic/altitude.pp" --obj_directory="ku/logic" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

ku/logic/battery.obj: ../ku/logic/battery.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"C:/ti/ccsv5/tools/compiler/msp430_4.2.1/bin/cl430" --cmd_file="C:\Users\Ilya\Dropbox\Sports Watch\simpliciti\Applications\configuration\smpl_nwk_config.dat" --cmd_file="C:\Users\Ilya\Dropbox\Sports Watch\simpliciti\Applications\configuration\End Device\smpl_config.dat"  -vmspx --abi=coffabi -O4 --opt_for_speed=0 --include_path="C:/ti/ccsv5/ccs_base/msp430/include" --include_path="C:/ti/ccsv5/tools/compiler/msp430_4.2.1/include" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/include" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/logic" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/driver" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/bluerobin" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Applications/application/End Device" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Components/bsp" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Components/bsp/boards" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Components/bsp/boards/CC430EM" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Components/bsp/boards/CC430EM/bsp_external" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Components/bsp/drivers" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Components/bsp/drivers/code" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Components/bsp/mcus" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Components/mrfi" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Components/mrfi/radios" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Components/mrfi/radios/family5" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Components/mrfi/smartrf" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Components/nwk" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Components/nwk_applications" -g --define=__CC430F6137__ --define=__CCE__ --define=ISM_EU --define=MRFI_CC430 --diag_warning=225 --display_error_number --diag_wrap=off --silicon_errata=CPU18 --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU23 --silicon_errata=CPU40 --call_assumptions=0 --gen_opt_info=2 --printf_support=minimal --preproc_with_compile --preproc_dependency="ku/logic/battery.pp" --obj_directory="ku/logic" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

ku/logic/bluerobin.obj: ../ku/logic/bluerobin.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"C:/ti/ccsv5/tools/compiler/msp430_4.2.1/bin/cl430" --cmd_file="C:\Users\Ilya\Dropbox\Sports Watch\simpliciti\Applications\configuration\smpl_nwk_config.dat" --cmd_file="C:\Users\Ilya\Dropbox\Sports Watch\simpliciti\Applications\configuration\End Device\smpl_config.dat"  -vmspx --abi=coffabi -O4 --opt_for_speed=0 --include_path="C:/ti/ccsv5/ccs_base/msp430/include" --include_path="C:/ti/ccsv5/tools/compiler/msp430_4.2.1/include" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/include" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/logic" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/driver" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/bluerobin" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Applications/application/End Device" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Components/bsp" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Components/bsp/boards" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Components/bsp/boards/CC430EM" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Components/bsp/boards/CC430EM/bsp_external" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Components/bsp/drivers" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Components/bsp/drivers/code" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Components/bsp/mcus" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Components/mrfi" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Components/mrfi/radios" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Components/mrfi/radios/family5" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Components/mrfi/smartrf" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Components/nwk" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Components/nwk_applications" -g --define=__CC430F6137__ --define=__CCE__ --define=ISM_EU --define=MRFI_CC430 --diag_warning=225 --display_error_number --diag_wrap=off --silicon_errata=CPU18 --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU23 --silicon_errata=CPU40 --call_assumptions=0 --gen_opt_info=2 --printf_support=minimal --preproc_with_compile --preproc_dependency="ku/logic/bluerobin.pp" --obj_directory="ku/logic" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

ku/logic/clock.obj: ../ku/logic/clock.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"C:/ti/ccsv5/tools/compiler/msp430_4.2.1/bin/cl430" --cmd_file="C:\Users\Ilya\Dropbox\Sports Watch\simpliciti\Applications\configuration\smpl_nwk_config.dat" --cmd_file="C:\Users\Ilya\Dropbox\Sports Watch\simpliciti\Applications\configuration\End Device\smpl_config.dat"  -vmspx --abi=coffabi -O4 --opt_for_speed=0 --include_path="C:/ti/ccsv5/ccs_base/msp430/include" --include_path="C:/ti/ccsv5/tools/compiler/msp430_4.2.1/include" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/include" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/logic" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/driver" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/bluerobin" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Applications/application/End Device" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Components/bsp" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Components/bsp/boards" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Components/bsp/boards/CC430EM" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Components/bsp/boards/CC430EM/bsp_external" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Components/bsp/drivers" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Components/bsp/drivers/code" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Components/bsp/mcus" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Components/mrfi" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Components/mrfi/radios" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Components/mrfi/radios/family5" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Components/mrfi/smartrf" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Components/nwk" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Components/nwk_applications" -g --define=__CC430F6137__ --define=__CCE__ --define=ISM_EU --define=MRFI_CC430 --diag_warning=225 --display_error_number --diag_wrap=off --silicon_errata=CPU18 --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU23 --silicon_errata=CPU40 --call_assumptions=0 --gen_opt_info=2 --printf_support=minimal --preproc_with_compile --preproc_dependency="ku/logic/clock.pp" --obj_directory="ku/logic" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

ku/logic/date.obj: ../ku/logic/date.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"C:/ti/ccsv5/tools/compiler/msp430_4.2.1/bin/cl430" --cmd_file="C:\Users\Ilya\Dropbox\Sports Watch\simpliciti\Applications\configuration\smpl_nwk_config.dat" --cmd_file="C:\Users\Ilya\Dropbox\Sports Watch\simpliciti\Applications\configuration\End Device\smpl_config.dat"  -vmspx --abi=coffabi -O4 --opt_for_speed=0 --include_path="C:/ti/ccsv5/ccs_base/msp430/include" --include_path="C:/ti/ccsv5/tools/compiler/msp430_4.2.1/include" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/include" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/logic" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/driver" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/bluerobin" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Applications/application/End Device" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Components/bsp" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Components/bsp/boards" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Components/bsp/boards/CC430EM" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Components/bsp/boards/CC430EM/bsp_external" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Components/bsp/drivers" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Components/bsp/drivers/code" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Components/bsp/mcus" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Components/mrfi" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Components/mrfi/radios" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Components/mrfi/radios/family5" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Components/mrfi/smartrf" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Components/nwk" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Components/nwk_applications" -g --define=__CC430F6137__ --define=__CCE__ --define=ISM_EU --define=MRFI_CC430 --diag_warning=225 --display_error_number --diag_wrap=off --silicon_errata=CPU18 --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU23 --silicon_errata=CPU40 --call_assumptions=0 --gen_opt_info=2 --printf_support=minimal --preproc_with_compile --preproc_dependency="ku/logic/date.pp" --obj_directory="ku/logic" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

ku/logic/menu.obj: ../ku/logic/menu.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"C:/ti/ccsv5/tools/compiler/msp430_4.2.1/bin/cl430" --cmd_file="C:\Users\Ilya\Dropbox\Sports Watch\simpliciti\Applications\configuration\smpl_nwk_config.dat" --cmd_file="C:\Users\Ilya\Dropbox\Sports Watch\simpliciti\Applications\configuration\End Device\smpl_config.dat"  -vmspx --abi=coffabi -O4 --opt_for_speed=0 --include_path="C:/ti/ccsv5/ccs_base/msp430/include" --include_path="C:/ti/ccsv5/tools/compiler/msp430_4.2.1/include" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/include" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/logic" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/driver" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/bluerobin" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Applications/application/End Device" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Components/bsp" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Components/bsp/boards" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Components/bsp/boards/CC430EM" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Components/bsp/boards/CC430EM/bsp_external" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Components/bsp/drivers" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Components/bsp/drivers/code" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Components/bsp/mcus" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Components/mrfi" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Components/mrfi/radios" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Components/mrfi/radios/family5" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Components/mrfi/smartrf" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Components/nwk" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Components/nwk_applications" -g --define=__CC430F6137__ --define=__CCE__ --define=ISM_EU --define=MRFI_CC430 --diag_warning=225 --display_error_number --diag_wrap=off --silicon_errata=CPU18 --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU23 --silicon_errata=CPU40 --call_assumptions=0 --gen_opt_info=2 --printf_support=minimal --preproc_with_compile --preproc_dependency="ku/logic/menu.pp" --obj_directory="ku/logic" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

ku/logic/rfbsl.obj: ../ku/logic/rfbsl.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"C:/ti/ccsv5/tools/compiler/msp430_4.2.1/bin/cl430" --cmd_file="C:\Users\Ilya\Dropbox\Sports Watch\simpliciti\Applications\configuration\smpl_nwk_config.dat" --cmd_file="C:\Users\Ilya\Dropbox\Sports Watch\simpliciti\Applications\configuration\End Device\smpl_config.dat"  -vmspx --abi=coffabi -O4 --opt_for_speed=0 --include_path="C:/ti/ccsv5/ccs_base/msp430/include" --include_path="C:/ti/ccsv5/tools/compiler/msp430_4.2.1/include" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/include" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/logic" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/driver" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/bluerobin" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Applications/application/End Device" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Components/bsp" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Components/bsp/boards" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Components/bsp/boards/CC430EM" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Components/bsp/boards/CC430EM/bsp_external" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Components/bsp/drivers" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Components/bsp/drivers/code" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Components/bsp/mcus" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Components/mrfi" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Components/mrfi/radios" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Components/mrfi/radios/family5" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Components/mrfi/smartrf" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Components/nwk" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Components/nwk_applications" -g --define=__CC430F6137__ --define=__CCE__ --define=ISM_EU --define=MRFI_CC430 --diag_warning=225 --display_error_number --diag_wrap=off --silicon_errata=CPU18 --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU23 --silicon_errata=CPU40 --call_assumptions=0 --gen_opt_info=2 --printf_support=minimal --preproc_with_compile --preproc_dependency="ku/logic/rfbsl.pp" --obj_directory="ku/logic" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

ku/logic/rfsimpliciti.obj: ../ku/logic/rfsimpliciti.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"C:/ti/ccsv5/tools/compiler/msp430_4.2.1/bin/cl430" --cmd_file="C:\Users\Ilya\Dropbox\Sports Watch\simpliciti\Applications\configuration\smpl_nwk_config.dat" --cmd_file="C:\Users\Ilya\Dropbox\Sports Watch\simpliciti\Applications\configuration\End Device\smpl_config.dat"  -vmspx --abi=coffabi -O4 --opt_for_speed=0 --include_path="C:/ti/ccsv5/ccs_base/msp430/include" --include_path="C:/ti/ccsv5/tools/compiler/msp430_4.2.1/include" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/include" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/logic" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/driver" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/bluerobin" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Applications/application/End Device" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Components/bsp" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Components/bsp/boards" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Components/bsp/boards/CC430EM" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Components/bsp/boards/CC430EM/bsp_external" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Components/bsp/drivers" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Components/bsp/drivers/code" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Components/bsp/mcus" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Components/mrfi" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Components/mrfi/radios" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Components/mrfi/radios/family5" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Components/mrfi/smartrf" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Components/nwk" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Components/nwk_applications" -g --define=__CC430F6137__ --define=__CCE__ --define=ISM_EU --define=MRFI_CC430 --diag_warning=225 --display_error_number --diag_wrap=off --silicon_errata=CPU18 --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU23 --silicon_errata=CPU40 --call_assumptions=0 --gen_opt_info=2 --printf_support=minimal --preproc_with_compile --preproc_dependency="ku/logic/rfsimpliciti.pp" --obj_directory="ku/logic" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

ku/logic/stopwatch.obj: ../ku/logic/stopwatch.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"C:/ti/ccsv5/tools/compiler/msp430_4.2.1/bin/cl430" --cmd_file="C:\Users\Ilya\Dropbox\Sports Watch\simpliciti\Applications\configuration\smpl_nwk_config.dat" --cmd_file="C:\Users\Ilya\Dropbox\Sports Watch\simpliciti\Applications\configuration\End Device\smpl_config.dat"  -vmspx --abi=coffabi -O4 --opt_for_speed=0 --include_path="C:/ti/ccsv5/ccs_base/msp430/include" --include_path="C:/ti/ccsv5/tools/compiler/msp430_4.2.1/include" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/include" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/logic" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/driver" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/bluerobin" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Applications/application/End Device" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Components/bsp" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Components/bsp/boards" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Components/bsp/boards/CC430EM" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Components/bsp/boards/CC430EM/bsp_external" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Components/bsp/drivers" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Components/bsp/drivers/code" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Components/bsp/mcus" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Components/mrfi" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Components/mrfi/radios" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Components/mrfi/radios/family5" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Components/mrfi/smartrf" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Components/nwk" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Components/nwk_applications" -g --define=__CC430F6137__ --define=__CCE__ --define=ISM_EU --define=MRFI_CC430 --diag_warning=225 --display_error_number --diag_wrap=off --silicon_errata=CPU18 --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU23 --silicon_errata=CPU40 --call_assumptions=0 --gen_opt_info=2 --printf_support=minimal --preproc_with_compile --preproc_dependency="ku/logic/stopwatch.pp" --obj_directory="ku/logic" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

ku/logic/temperature.obj: ../ku/logic/temperature.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"C:/ti/ccsv5/tools/compiler/msp430_4.2.1/bin/cl430" --cmd_file="C:\Users\Ilya\Dropbox\Sports Watch\simpliciti\Applications\configuration\smpl_nwk_config.dat" --cmd_file="C:\Users\Ilya\Dropbox\Sports Watch\simpliciti\Applications\configuration\End Device\smpl_config.dat"  -vmspx --abi=coffabi -O4 --opt_for_speed=0 --include_path="C:/ti/ccsv5/ccs_base/msp430/include" --include_path="C:/ti/ccsv5/tools/compiler/msp430_4.2.1/include" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/include" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/logic" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/driver" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/bluerobin" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Applications/application/End Device" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Components/bsp" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Components/bsp/boards" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Components/bsp/boards/CC430EM" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Components/bsp/boards/CC430EM/bsp_external" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Components/bsp/drivers" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Components/bsp/drivers/code" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Components/bsp/mcus" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Components/mrfi" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Components/mrfi/radios" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Components/mrfi/radios/family5" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Components/mrfi/smartrf" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Components/nwk" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Components/nwk_applications" -g --define=__CC430F6137__ --define=__CCE__ --define=ISM_EU --define=MRFI_CC430 --diag_warning=225 --display_error_number --diag_wrap=off --silicon_errata=CPU18 --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU23 --silicon_errata=CPU40 --call_assumptions=0 --gen_opt_info=2 --printf_support=minimal --preproc_with_compile --preproc_dependency="ku/logic/temperature.pp" --obj_directory="ku/logic" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

ku/logic/test.obj: ../ku/logic/test.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"C:/ti/ccsv5/tools/compiler/msp430_4.2.1/bin/cl430" --cmd_file="C:\Users\Ilya\Dropbox\Sports Watch\simpliciti\Applications\configuration\smpl_nwk_config.dat" --cmd_file="C:\Users\Ilya\Dropbox\Sports Watch\simpliciti\Applications\configuration\End Device\smpl_config.dat"  -vmspx --abi=coffabi -O4 --opt_for_speed=0 --include_path="C:/ti/ccsv5/ccs_base/msp430/include" --include_path="C:/ti/ccsv5/tools/compiler/msp430_4.2.1/include" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/include" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/logic" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/driver" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/bluerobin" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Applications/application/End Device" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Components/bsp" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Components/bsp/boards" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Components/bsp/boards/CC430EM" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Components/bsp/boards/CC430EM/bsp_external" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Components/bsp/drivers" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Components/bsp/drivers/code" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Components/bsp/mcus" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Components/mrfi" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Components/mrfi/radios" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Components/mrfi/radios/family5" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Components/mrfi/smartrf" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Components/nwk" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Components/nwk_applications" -g --define=__CC430F6137__ --define=__CCE__ --define=ISM_EU --define=MRFI_CC430 --diag_warning=225 --display_error_number --diag_wrap=off --silicon_errata=CPU18 --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU23 --silicon_errata=CPU40 --call_assumptions=0 --gen_opt_info=2 --printf_support=minimal --preproc_with_compile --preproc_dependency="ku/logic/test.pp" --obj_directory="ku/logic" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

ku/logic/user.obj: ../ku/logic/user.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"C:/ti/ccsv5/tools/compiler/msp430_4.2.1/bin/cl430" --cmd_file="C:\Users\Ilya\Dropbox\Sports Watch\simpliciti\Applications\configuration\smpl_nwk_config.dat" --cmd_file="C:\Users\Ilya\Dropbox\Sports Watch\simpliciti\Applications\configuration\End Device\smpl_config.dat"  -vmspx --abi=coffabi -O4 --opt_for_speed=0 --include_path="C:/ti/ccsv5/ccs_base/msp430/include" --include_path="C:/ti/ccsv5/tools/compiler/msp430_4.2.1/include" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/include" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/logic" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/driver" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/bluerobin" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Applications/application/End Device" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Components/bsp" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Components/bsp/boards" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Components/bsp/boards/CC430EM" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Components/bsp/boards/CC430EM/bsp_external" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Components/bsp/drivers" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Components/bsp/drivers/code" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Components/bsp/mcus" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Components/mrfi" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Components/mrfi/radios" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Components/mrfi/radios/family5" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Components/mrfi/smartrf" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Components/nwk" --include_path="C:/Users/Ilya/Dropbox/Sports Watch/simpliciti/Components/nwk_applications" -g --define=__CC430F6137__ --define=__CCE__ --define=ISM_EU --define=MRFI_CC430 --diag_warning=225 --display_error_number --diag_wrap=off --silicon_errata=CPU18 --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU23 --silicon_errata=CPU40 --call_assumptions=0 --gen_opt_info=2 --printf_support=minimal --preproc_with_compile --preproc_dependency="ku/logic/user.pp" --obj_directory="ku/logic" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '


